services:
  - type: web
    name: today-lc-bot
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 8443
